[package]
name = "day7"
version = "0.1.0"
authors = ["Thomas O'Brien <thomas.obrien86@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstest = "0.6.4"